import {
  Warehouse,
  StockItem,
  StockBalance,
  StockEntry,
  WarehouseType,
  ItemType,
  UnitOfMeasure
} from '@/types/inventory'

// ==========================================
// Warehouses (from ERP Plan)
// ==========================================

export const mockWarehouses: Warehouse[] = [
  // Raw Materials
  {
    id: 'wh-rm-cold',
    code: 'RM-COLD-ROOM',
    name: 'ห้องเย็นวัตถุดิบ',
    type: 'RAW_MATERIAL',
    status: 'ACTIVE',
    isQuarantine: false,
    isDefault: true,
    temperatureControlled: true,
    minTemp: 0,
    maxTemp: 4,
    location: 'อาคาร A ชั้น 1',
    capacity: 5000,
    currentStock: 3200,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'wh-rm-dry',
    code: 'RM-DRY-STORE',
    name: 'คลังวัตถุดิบแห้ง',
    type: 'RAW_MATERIAL',
    status: 'ACTIVE',
    isQuarantine: false,
    isDefault: false,
    temperatureControlled: false,
    location: 'อาคาร A ชั้น 1',
    capacity: 3000,
    currentStock: 1800,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'wh-rm-pkg',
    code: 'RM-PACKAGING',
    name: 'คลังบรรจุภัณฑ์',
    type: 'RAW_MATERIAL',
    status: 'ACTIVE',
    isQuarantine: false,
    isDefault: false,
    temperatureControlled: false,
    location: 'อาคาร B ชั้น 1',
    capacity: 10000,
    currentStock: 6500,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'wh-rm-quarantine',
    code: 'RM-QUARANTINE',
    name: 'คลังกักกันวัตถุดิบ',
    type: 'RAW_MATERIAL',
    status: 'ACTIVE',
    isQuarantine: true,
    isDefault: false,
    temperatureControlled: true,
    minTemp: 0,
    maxTemp: 4,
    location: 'อาคาร A ชั้น 1 (แยก)',
    capacity: 500,
    currentStock: 45,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  // Work in Progress
  {
    id: 'wh-wip',
    code: 'WIP',
    name: 'ระหว่างผลิต',
    type: 'WIP',
    status: 'ACTIVE',
    isQuarantine: false,
    isDefault: true,
    temperatureControlled: true,
    minTemp: 0,
    maxTemp: 10,
    location: 'อาคารผลิต',
    capacity: 2000,
    currentStock: 350,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  // Finished Goods
  {
    id: 'wh-fg-cold',
    code: 'FG-COLD-ROOM',
    name: 'ห้องเย็นสินค้าสำเร็จรูป',
    type: 'FINISHED_GOODS',
    status: 'ACTIVE',
    isQuarantine: false,
    isDefault: true,
    temperatureControlled: true,
    minTemp: 0,
    maxTemp: 4,
    location: 'อาคาร C ชั้น 1',
    capacity: 15000,
    currentStock: 8500,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'wh-fg-hold',
    code: 'FG-HOLD',
    name: 'คลังรอ QC',
    type: 'FINISHED_GOODS',
    status: 'ACTIVE',
    isQuarantine: false,
    isDefault: false,
    temperatureControlled: true,
    minTemp: 0,
    maxTemp: 4,
    location: 'อาคาร C ชั้น 1',
    capacity: 1000,
    currentStock: 120,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'wh-fg-quarantine',
    code: 'FG-QUARANTINE',
    name: 'คลังกักกันสินค้า',
    type: 'FINISHED_GOODS',
    status: 'ACTIVE',
    isQuarantine: true,
    isDefault: false,
    temperatureControlled: true,
    minTemp: 0,
    maxTemp: 4,
    location: 'อาคาร C ชั้น 1 (แยก)',
    capacity: 500,
    currentStock: 30,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
]

// ==========================================
// Stock Items (from BOM)
// ==========================================

export const mockStockItems: StockItem[] = [
  // Proteins (Cold)
  {
    id: 'item-chicken',
    code: 'RM-CHICKEN',
    name: 'อกไก่สด',
    type: 'RAW_MATERIAL',
    uom: 'KG',
    defaultWarehouseId: 'wh-rm-cold',
    hasBatch: true,
    hasExpiry: true,
    shelfLifeDays: 5,
    minStock: 50,
    maxStock: 200,
    reorderPoint: 80,
    requiresQC: true,
    qcTemplateId: 'qct-raw-chicken',
    costPerUnit: 150,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'item-plant-protein',
    code: 'RM-PLANT-PROTEIN',
    name: 'โปรตีนพืช',
    type: 'RAW_MATERIAL',
    uom: 'KG',
    defaultWarehouseId: 'wh-rm-dry',
    hasBatch: true,
    hasExpiry: true,
    shelfLifeDays: 180,
    minStock: 20,
    maxStock: 100,
    reorderPoint: 40,
    requiresQC: true,
    qcTemplateId: 'qct-raw-general',
    costPerUnit: 330,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  // Thickeners (Dry)
  {
    id: 'item-cmc',
    code: 'RM-CMC',
    name: 'CMC',
    type: 'RAW_MATERIAL',
    uom: 'KG',
    defaultWarehouseId: 'wh-rm-dry',
    hasBatch: true,
    hasExpiry: true,
    shelfLifeDays: 365,
    minStock: 10,
    maxStock: 50,
    reorderPoint: 20,
    requiresQC: false,
    costPerUnit: 170,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'item-xanthan',
    code: 'RM-XANTHAN',
    name: 'Xanthan Gum',
    type: 'RAW_MATERIAL',
    uom: 'KG',
    defaultWarehouseId: 'wh-rm-dry',
    hasBatch: true,
    hasExpiry: true,
    shelfLifeDays: 365,
    minStock: 5,
    maxStock: 30,
    reorderPoint: 10,
    requiresQC: false,
    costPerUnit: 140,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  // Flavors
  {
    id: 'item-strawberry-flavor',
    code: 'RM-STRAWBERRY-FLAVOR',
    name: 'กลิ่นสตรอว์เบอร์รี่',
    type: 'RAW_MATERIAL',
    uom: 'KG',
    defaultWarehouseId: 'wh-rm-dry',
    hasBatch: true,
    hasExpiry: true,
    shelfLifeDays: 365,
    minStock: 2,
    maxStock: 20,
    reorderPoint: 5,
    requiresQC: false,
    costPerUnit: 880,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'item-thaitea-flavor',
    code: 'RM-THAITEA-FLAVOR',
    name: 'กลิ่นชาไทย',
    type: 'RAW_MATERIAL',
    uom: 'KG',
    defaultWarehouseId: 'wh-rm-dry',
    hasBatch: true,
    hasExpiry: true,
    shelfLifeDays: 365,
    minStock: 2,
    maxStock: 15,
    reorderPoint: 4,
    requiresQC: false,
    costPerUnit: 1600,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  // Water
  {
    id: 'item-water',
    code: 'RM-WATER',
    name: 'น้ำ RO',
    type: 'RAW_MATERIAL',
    uom: 'L',
    defaultWarehouseId: 'wh-rm-cold',
    hasBatch: false,
    hasExpiry: false,
    minStock: 500,
    maxStock: 2000,
    reorderPoint: 800,
    requiresQC: true,
    qcTemplateId: 'qct-water',
    costPerUnit: 8,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  // Packaging
  {
    id: 'item-bottle-250',
    code: 'PKG-BOTTLE-250',
    name: 'ขวด PET 250ml',
    type: 'PACKAGING',
    uom: 'PC',
    defaultWarehouseId: 'wh-rm-pkg',
    hasBatch: true,
    hasExpiry: false,
    minStock: 5000,
    maxStock: 20000,
    reorderPoint: 8000,
    requiresQC: true,
    qcTemplateId: 'qct-packaging',
    costPerUnit: 3.5,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'item-cap',
    code: 'PKG-CAP',
    name: 'ฝาขวด',
    type: 'PACKAGING',
    uom: 'PC',
    defaultWarehouseId: 'wh-rm-pkg',
    hasBatch: true,
    hasExpiry: false,
    minStock: 5000,
    maxStock: 25000,
    reorderPoint: 10000,
    requiresQC: false,
    costPerUnit: 0.8,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'item-label',
    code: 'PKG-LABEL',
    name: 'สติ๊กเกอร์ฉลาก',
    type: 'PACKAGING',
    uom: 'PC',
    defaultWarehouseId: 'wh-rm-pkg',
    hasBatch: true,
    hasExpiry: false,
    minStock: 5000,
    maxStock: 30000,
    reorderPoint: 10000,
    requiresQC: false,
    costPerUnit: 0.5,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  // Semi-Finished
  {
    id: 'item-cooked-chicken',
    code: 'SF-CHICKEN-COOKED',
    name: 'ไก่สุกพร้อมผสม',
    type: 'SEMI_FINISHED',
    uom: 'KG',
    defaultWarehouseId: 'wh-wip',
    hasBatch: true,
    hasExpiry: true,
    shelfLifeDays: 2,
    minStock: 10,
    maxStock: 50,
    reorderPoint: 20,
    requiresQC: true,
    qcTemplateId: 'qct-semi-chicken',
    costPerUnit: 200,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  // Finished Goods
  {
    id: 'item-fg-ck-blueberry',
    code: 'FG-CK-BLUEBERRY',
    name: 'โปรตีนไก่ บลูเบอร์รี่',
    type: 'FINISHED_GOOD',
    uom: 'BTL',
    defaultWarehouseId: 'wh-fg-cold',
    hasBatch: true,
    hasExpiry: true,
    shelfLifeDays: 30,
    minStock: 100,
    maxStock: 500,
    reorderPoint: 200,
    requiresQC: true,
    qcTemplateId: 'qct-finished-good',
    costPerUnit: 35,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'item-fg-ck-thaitea',
    code: 'FG-CK-THAITEA',
    name: 'โปรตีนไก่ ชาไทย',
    type: 'FINISHED_GOOD',
    uom: 'BTL',
    defaultWarehouseId: 'wh-fg-cold',
    hasBatch: true,
    hasExpiry: true,
    shelfLifeDays: 30,
    minStock: 150,
    maxStock: 600,
    reorderPoint: 250,
    requiresQC: true,
    qcTemplateId: 'qct-finished-good',
    costPerUnit: 38,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
  {
    id: 'item-fg-pb-thaitea',
    code: 'FG-PB-THAITEA',
    name: 'โปรตีนพืช ชาไทย',
    type: 'FINISHED_GOOD',
    uom: 'BTL',
    defaultWarehouseId: 'wh-fg-cold',
    hasBatch: true,
    hasExpiry: true,
    shelfLifeDays: 45,
    minStock: 80,
    maxStock: 400,
    reorderPoint: 150,
    requiresQC: true,
    qcTemplateId: 'qct-finished-good',
    costPerUnit: 42,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-31T00:00:00Z',
  },
]

// ==========================================
// Stock Balances (Current Stock)
// ==========================================

export const mockStockBalances: StockBalance[] = [
  // Raw Materials - Cold Room
  {
    id: 'bal-chicken-001',
    itemId: 'item-chicken',
    warehouseId: 'wh-rm-cold',
    batchNo: 'CK-20260130-001',
    qty: 45,
    uom: 'KG',
    mfgDate: '2026-01-30',
    expDate: '2026-02-04',
    status: 'AVAILABLE',
    lastUpdated: '2026-01-30T08:00:00Z',
  },
  {
    id: 'bal-chicken-002',
    itemId: 'item-chicken',
    warehouseId: 'wh-rm-cold',
    batchNo: 'CK-20260131-001',
    qty: 60,
    uom: 'KG',
    mfgDate: '2026-01-31',
    expDate: '2026-02-05',
    status: 'AVAILABLE',
    lastUpdated: '2026-01-31T08:00:00Z',
  },
  // Raw Materials - Dry Store
  {
    id: 'bal-cmc-001',
    itemId: 'item-cmc',
    warehouseId: 'wh-rm-dry',
    batchNo: 'CMC-20260101',
    qty: 25,
    uom: 'KG',
    mfgDate: '2025-12-01',
    expDate: '2026-12-01',
    status: 'AVAILABLE',
    lastUpdated: '2026-01-31T00:00:00Z',
  },
  {
    id: 'bal-xanthan-001',
    itemId: 'item-xanthan',
    warehouseId: 'wh-rm-dry',
    batchNo: 'XAN-20260115',
    qty: 8,
    uom: 'KG',
    mfgDate: '2025-12-15',
    expDate: '2026-12-15',
    status: 'AVAILABLE',
    lastUpdated: '2026-01-31T00:00:00Z',
  },
  // Packaging
  {
    id: 'bal-bottle-001',
    itemId: 'item-bottle-250',
    warehouseId: 'wh-rm-pkg',
    batchNo: 'BTL-20260101',
    qty: 12000,
    uom: 'PC',
    status: 'AVAILABLE',
    lastUpdated: '2026-01-31T00:00:00Z',
  },
  {
    id: 'bal-cap-001',
    itemId: 'item-cap',
    warehouseId: 'wh-rm-pkg',
    batchNo: 'CAP-20260101',
    qty: 15000,
    uom: 'PC',
    status: 'AVAILABLE',
    lastUpdated: '2026-01-31T00:00:00Z',
  },
  // Semi-Finished (WIP)
  {
    id: 'bal-cooked-chicken-001',
    itemId: 'item-cooked-chicken',
    warehouseId: 'wh-wip',
    batchNo: 'SF-CK-20260131-001',
    qty: 25,
    uom: 'KG',
    mfgDate: '2026-01-31',
    expDate: '2026-02-02',
    status: 'AVAILABLE',
    lastUpdated: '2026-01-31T10:00:00Z',
  },
  // Finished Goods
  {
    id: 'bal-fg-ck-blueberry-001',
    itemId: 'item-fg-ck-blueberry',
    warehouseId: 'wh-fg-cold',
    batchNo: 'FG-CKB-20260130-001',
    qty: 180,
    uom: 'BTL',
    mfgDate: '2026-01-30',
    expDate: '2026-03-01',
    status: 'AVAILABLE',
    lastUpdated: '2026-01-30T16:00:00Z',
  },
  {
    id: 'bal-fg-ck-thaitea-001',
    itemId: 'item-fg-ck-thaitea',
    warehouseId: 'wh-fg-cold',
    batchNo: 'FG-CKT-20260131-001',
    qty: 240,
    uom: 'BTL',
    mfgDate: '2026-01-31',
    expDate: '2026-03-02',
    status: 'AVAILABLE',
    lastUpdated: '2026-01-31T16:00:00Z',
  },
  // Quarantine
  {
    id: 'bal-chicken-quarantine',
    itemId: 'item-chicken',
    warehouseId: 'wh-rm-quarantine',
    batchNo: 'CK-20260129-002',
    qty: 15,
    uom: 'KG',
    mfgDate: '2026-01-29',
    expDate: '2026-02-03',
    status: 'QUARANTINE',
    lastUpdated: '2026-01-29T14:00:00Z',
  },
]

// ==========================================
// Recent Stock Entries
// ==========================================

export const mockStockEntries: StockEntry[] = [
  {
    id: 'se-001',
    code: 'SE-2026-0001',
    type: 'RECEIVE',
    status: 'SUBMITTED',
    postingDate: '2026-01-31',
    postingTime: '08:30',
    sourceDocType: 'Purchase Receipt',
    sourceDocId: 'PR-2026-0045',
    items: [
      {
        id: 'sei-001-1',
        lineNo: 1,
        itemId: 'item-chicken',
        qty: 60,
        uom: 'KG',
        batchNo: 'CK-20260131-001',
        toWarehouseId: 'wh-rm-cold',
        mfgDate: '2026-01-31',
        expDate: '2026-02-05',
        unitCost: 150,
        totalCost: 9000,
      },
    ],
    remarks: 'รับไก่สดจาก Supplier A',
    isQCRequired: true,
    isQCPassed: true,
    qcInspectionId: 'qi-001',
    createdBy: 'สมชาย',
    createdAt: '2026-01-31T08:30:00Z',
    updatedAt: '2026-01-31T09:00:00Z',
  },
  {
    id: 'se-002',
    code: 'SE-2026-0002',
    type: 'ISSUE',
    status: 'SUBMITTED',
    postingDate: '2026-01-31',
    postingTime: '10:00',
    sourceDocType: 'Work Order',
    sourceDocId: 'WO-2026-0012',
    items: [
      {
        id: 'sei-002-1',
        lineNo: 1,
        itemId: 'item-chicken',
        qty: 30,
        uom: 'KG',
        batchNo: 'CK-20260130-001',
        fromWarehouseId: 'wh-rm-cold',
        unitCost: 150,
        totalCost: 4500,
      },
    ],
    remarks: 'เบิกวัตถุดิบสำหรับ Batch ผลิต',
    isQCRequired: false,
    createdBy: 'มานี',
    createdAt: '2026-01-31T10:00:00Z',
    updatedAt: '2026-01-31T10:00:00Z',
  },
  {
    id: 'se-003',
    code: 'SE-2026-0003',
    type: 'MANUFACTURE',
    status: 'SUBMITTED',
    postingDate: '2026-01-31',
    postingTime: '16:00',
    sourceDocType: 'Work Order',
    sourceDocId: 'WO-2026-0012',
    items: [
      {
        id: 'sei-003-1',
        lineNo: 1,
        itemId: 'item-fg-ck-thaitea',
        qty: 240,
        uom: 'BTL',
        batchNo: 'FG-CKT-20260131-001',
        toWarehouseId: 'wh-fg-cold',
        mfgDate: '2026-01-31',
        expDate: '2026-03-02',
        unitCost: 38,
        totalCost: 9120,
      },
    ],
    remarks: 'รับ FG จาก Work Order',
    isQCRequired: true,
    isQCPassed: true,
    qcInspectionId: 'qi-002',
    createdBy: 'วิชัย',
    createdAt: '2026-01-31T16:00:00Z',
    updatedAt: '2026-01-31T16:30:00Z',
  },
]

// ==========================================
// Helper Functions
// ==========================================

export function getWarehouseById(id: string): Warehouse | undefined {
  return mockWarehouses.find(w => w.id === id)
}

export function getItemById(id: string): StockItem | undefined {
  return mockStockItems.find(i => i.id === id)
}

export function getStockByItem(itemId: string): StockBalance[] {
  return mockStockBalances.filter(b => b.itemId === itemId)
}

export function getStockByWarehouse(warehouseId: string): StockBalance[] {
  return mockStockBalances.filter(b => b.warehouseId === warehouseId)
}

export function getTotalStock(itemId: string): number {
  return mockStockBalances
    .filter(b => b.itemId === itemId && b.status === 'AVAILABLE')
    .reduce((sum, b) => sum + b.qty, 0)
}

export function isLowStock(item: StockItem): boolean {
  const total = getTotalStock(item.id)
  return item.minStock !== undefined && total < item.minStock
}

export function getExpiringItems(days: number = 7): StockBalance[] {
  const cutoff = new Date()
  cutoff.setDate(cutoff.getDate() + days)

  return mockStockBalances.filter(b => {
    if (!b.expDate) return false
    const expDate = new Date(b.expDate)
    return expDate <= cutoff && b.status === 'AVAILABLE'
  })
}
